/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventmanager;

import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash patel
 */
public class editevent extends javax.swing.JFrame {

    /**
     * Creates new form editevent
     */
    public editevent() {
        initComponents();
        filltable();
        filltable();
    }

     public Connection MySqlconnection(){
        Connection conn=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mydatabase","root","yashp1210");
            return conn;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "MySql connection Failed....");
            return null;
        }
    }
    
    public ArrayList<eventbean> retriveData() {
    
        ArrayList<eventbean> e=null;
        e=new ArrayList<eventbean>(); 
        try{
            Connection conn=MySqlconnection();
            String q="select * from event";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(q);
            eventbean event;
            while(rs.next()){
                
                byte[] y=new byte[1024];
                y=rs.getBytes(5);
                event=new eventbean(rs.getString("name"),rs.getString("date"),rs.getString("time"),rs.getString("venue"),rs.getFloat(5),y);
                e.add(event);
            }
            
        }catch(Exception p){
            
            System.out.println("Error in retrieving data  :"+p);
        }
            
        
    return e;
}
    
    
    public void filltable(){
        ArrayList<eventbean> al=retriveData();
        DefaultTableModel dtm=(DefaultTableModel)edit_table.getModel();
        dtm.setRowCount(0);
        Object[] row=new Object[6];
        for(int i=0;i<al.size();i++){
            row[0]=al.get(i).getName();
            row[1]=al.get(i).getDate();
            row[3]=al.get(i).getVenue();
            row[4]=al.get(i).getFees();
            row[2]=al.get(i).getTime();
           
            dtm.addRow(row);
        }
    }
    
    public void showitem(int index){
        edit_eventname.setText(retriveData().get(index).getName());
        edit_venue.setText(retriveData().get(index).getVenue());
        edit_fees.setText(Float.toString(retriveData().get(index).getFees()));
        edit_time.setText(retriveData().get(index).getTime());
                
        try{
            
            java.util.Date date=null;
            date=new SimpleDateFormat("dd-MM-yyy").parse((String)retriveData().get(index).getDate());
            
            edit_date.setDate(date);
            
         
            
        }catch(Exception e){
            System.out.println(e);
        }
        
        showphoto.setIcon(resetImageSize(null,retriveData().get(index).getPhoto()));
    }
    
    
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edit_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edit_eventname = new javax.swing.JTextField();
        edit_date = new com.toedter.calendar.JDateChooser();
        edit_venue = new javax.swing.JTextField();
        edit_fees = new javax.swing.JTextField();
        edit_photo = new javax.swing.JButton();
        update = new javax.swing.JButton();
        edit_search = new javax.swing.JTextField();
        showphoto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edit_time = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        edit_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Date", "Time", "Venue", "Registartion Fees"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        edit_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(edit_table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Event Name        :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Date                     :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Time                     :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Venue                  :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Registration fee :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Upload photo      :");

        edit_eventname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        edit_date.setDateFormatString("dd-MM-yyy");

        edit_venue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        edit_fees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        edit_photo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit_photo.setText("Select Photo");
        edit_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_photoActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        edit_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edit_searchKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Edit Event");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\jaimin patel\\Downloads\\icons8-detective-24.png")); // NOI18N

        edit_time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edit_eventname, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edit_venue, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(edit_fees, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(edit_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(update)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(showphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(edit_time, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edit_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(edit_search, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel6)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edit_eventname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edit_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edit_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_venue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_photo)
                            .addComponent(jLabel7))
                        .addGap(57, 57, 57)
                        .addComponent(update))
                    .addComponent(showphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     String photopath;
    public ImageIcon resetImageSize(String photopath,byte[] photo){
        ImageIcon myPhoto=null;
        if(photopath != null)
        {
            
            myPhoto=new ImageIcon(photopath);
        }
        else
        {
            myPhoto = new ImageIcon(photo);
        }
        
        Image img = myPhoto.getImage();
        ImageIcon ph=new ImageIcon(img);
        return ph;
    }
    
    
    
    private void edit_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_photoActionPerformed
        // TODO add your handling code here:

        JFileChooser c=new JFileChooser();
        c.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter f = new FileNameExtensionFilter("*.images","jpeg","jpg","png");
        c.addChoosableFileFilter(f);
        int ans=c.showSaveDialog(null);
        if(ans==JFileChooser.APPROVE_OPTION){
            File selectedphoto= c.getSelectedFile();
            String path=selectedphoto.getAbsolutePath();
            this.photopath=path;

        }
    }//GEN-LAST:event_edit_photoActionPerformed

    private void edit_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_tableMouseClicked
        // TODO add your handling code here:
        int ind=edit_table.getSelectedRow();
        showitem(ind);
        
    }//GEN-LAST:event_edit_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       
       if (edit_eventname !=null || edit_date!=null
                    || edit_fees !=null || edit_venue!=null) {
           
           String q=null;
           PreparedStatement ps=null;
           Connection conn=MySqlconnection();
           if(photopath==null){
           try{
               q="update event set date=?, venue=?, fees=? ,time=? WHERE name=? ";
               ps=conn.prepareStatement(q);
               
               SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
               String date1=sdf.format(edit_date.getDate());
               ps.setString(1,date1 );
               ps.setString(4, edit_time.getText());
               ps.setString(2,edit_venue.getText());
               
               ps.setFloat(3, Float.parseFloat(edit_fees.getText()));
               ps.setString(5, edit_eventname.getText());
               int res=ps.executeUpdate();
               if(res>=1){ 
                        JOptionPane.showMessageDialog(null,"Event Updated....");
                        filltable();
               }else{
                   JOptionPane.showMessageDialog(null,"Failed to Updated Event");
               }
               
           }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
           }
       }else{
               try{
               q="update event set date=?, venue=?, fees=? ,photo=?,time=? WHERE name=? ";
               ps=conn.prepareStatement(q);
               
               SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
               String date1=sdf.format(edit_date.getDate());
               ps.setString(1,date1 );
               ps.setString(5,edit_time.getText());
               ps.setString(2,edit_venue.getText());
               
               ps.setFloat(3, Float.parseFloat(edit_fees.getText()));
       
               InputStream is=new FileInputStream(new File(photopath));
               ps.setBlob(4, is);
               
               ps.setString(6, edit_eventname.getText());
               int res=ps.executeUpdate();
               if(res>=1){ 
                        JOptionPane.showMessageDialog(null,"Event Updated....");
                        filltable();
               }else{
                   JOptionPane.showMessageDialog(null,"Failed to Updated Event");
               }
               
           }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
           }
           }
       }              
        
        
        
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void edit_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edit_searchKeyReleased
        //edit_search.getText.toString();
        ArrayList<eventbean> e=null;
        e=new ArrayList<eventbean>();
        String val=edit_search.getText().toString();
        try{
            Connection conn=MySqlconnection();
            
            String qry="select * from event where name like '%"+val+"%'";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            eventbean event;
            
                    while(rs.next()){
                       event = new eventbean(rs.getString("name"),rs.getString("date"),rs.getString("time"),rs.getString("venue"),
                               Float.parseFloat(rs.getString(4)),rs.getBytes("photo"));
                       e.add(event);
                    }
                    
                    DefaultTableModel dtm=(DefaultTableModel)edit_table.getModel();
                    dtm.setRowCount(0);
                    Object[] row=new Object[5];
                    for(int i=0;i<e.size();i++){
                        row[0]=e.get(i).getName();
                        row[1]=e.get(i).getDate();
                        row[2]=e.get(i).getTime();
                        row[3]=e.get(i).getVenue();
                        row[4]=e.get(i).getFees();
                        dtm.addRow(row);
                        
                    }
                    
            
        }catch(Exception x){
            
                JOptionPane.showMessageDialog(null, x);
        }
    }//GEN-LAST:event_edit_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editevent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser edit_date;
    private javax.swing.JTextField edit_eventname;
    private javax.swing.JTextField edit_fees;
    private javax.swing.JButton edit_photo;
    private javax.swing.JTextField edit_search;
    private javax.swing.JTable edit_table;
    private javax.swing.JTextField edit_time;
    private javax.swing.JTextField edit_venue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel showphoto;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}

   
